version: v1.1.0
steps:
  - id: pull-tfcagent-image
    cmd: >
        docker pull {{.Values.REGISTRY_FROM_URL}}/hashicorp/tfc-agent:latest
  - id: retag-tfcagent-image
    when: ['pull-tfcagent-image']
    cmd: docker tag {{.Values.REGISTRY_FROM_URL}}/hashicorp/tfc-agent:latest {{.Run.Registry}}/hashicorp/tfc-agent:latest
  - id: push-tfcagent-image
    when: ['retag-tfcagent-image']
    push:
    - "{{.Run.Registry}}/hashicorp/tfc-agent:latest"